url:    http://www.laivictor.com
feed:   http://www.laivictor.com/atom.xml

paginate: 5
paginate_path: "/blog/page-:num"

exclude: ['README.markdown', 'Gemfile.lock', 'Gemfile']

sass:
    syntax: scss        # scss|sass
    style:  compressed  # nested|expanded|compact|compressed

markdown:       redcarpet
highlighter:    nil

encoding: utf-8

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "base/page"
            navigationhighlight: "home"
    -
        scope:
            path: "about"
        values:
            layout: "custom/about"
            navigationhighlight: "about"
    -
        scope:
            path: "portfolio"
        values:
            layout: "custom/portfolio"
            navigationhighlight: "portfolio"
    -
        scope:
            path: "blog"
        values:
            layout: "custom/post"
            navigationhighlight: "post"
