
url: http://www.laivictor.com
atom: http://www.laivictor.com/atom.xml

title: lai.victor
description: personal
author: Victor Lai


email: lai.victor.vl@gmail.com
github: blisse
twitter: laivictorvl
linkedin: laivictor

paginate: 100
paginate_path: "/blog/page-:num"

exclude: ['README.markdown', 'Gemfile.lock', 'Gemfile']

# defaults
sass:
  syntax: scss        # scss|sass
  style:  compressed  # nested|expanded|compact|compressed

markdown: maruku 
pygments: true
