auto: true
markdown: maruku
pygments: true
permalink: /archive/:year/:month/:day/index.html
url: http://www.laivictor.com
title: lai.victor
description: 
author: Victor Lai
email: lai.victor.vl@gmail.com
github: blisse
twitter: laivictorvl
linkedin: laivictor
exclude: ['README.markdown', '.gitignore']
paginate: 500