url: http://www.laivictor.com
atom: http://www.laivictor.com/atom.xml

title: lai.victor
description: personal blog
author: victor lai

email: admin@laivictor.com
github: blisse
twitter: dblisse
linkedin: laivictor
lastfm: dBlisse
facebook: lai.victor.vl

paginate: 5
paginate_path: "/blog/page-:num"

exclude: ['README.markdown', 'Gemfile.lock', 'Gemfile']

# defaults
sass:
  syntax: scss        # scss|sass
  style:  compressed  # nested|expanded|compact|compressed

markdown: rdiscount
pygments: true
