name_title: "victor lai"

website: "www.laivictor.com"
email: "hello@laivictor.com"
github: "www.github.com/blisse"

skills_title: "skills"
job_title: "work experience"
project_title: "side projects"
education_title: "education"

skills:
-   "Proficient using <strong>C/C++</strong>, <strong>C#</strong>, <strong>Python</strong>, <strong>HTML/CSS</strong>"
-   "Experienced in <strong>.NET WPF</strong>, <strong>Windows Store</strong> application development"
-   "Comfortable with variety of technologies: <strong>Git</strong>, <strong>Make</strong>, <strong>Android</strong>, <strong>iOS</strong>, <strong>OpenGL</strong>, <strong>Sass</strong>"
-   "Passionate about <strong>technology</strong>, <strong>engineering</strong>, <strong>audio</strong>, <strong>physical</strong> and <strong>mental well-being</strong>"

jobs:
-   title: "Software Engineer Intern"
    company: "Thalmic Labs"
    date: "Sept &ndash; Dec 2015"
    date_year: "2015"
    description:
        -   "Myo Android application development"

-   title: "Windows Shell Engineer Intern"
    company: "Microsoft"
    date: "Jan &ndash; Apr 2015"
    date_year: "2015"
    description:
        -   "Initiated first 1440p Windows 10 Mobile builds by adding missing build dependencies"
        -   "Integrated multi-monitor scaling on Windows 10 Mobile with Windows desktop implementation"
        -   "Rewrote Display page in Windows 10 Mobile Settings to support multi-monitor controls"

-   title: "Outlook Services Engineer Intern"
    company: "Microsoft"
    date: "May &ndash; Aug 2014"
    date_year: "2014"
    description:
        -   "Prototyped creative text messaging with native text transforms on Windows Phone, Android, and iOS"

-   title: "Agile Engineer"
    company: "Pivotal Labs"
    date: "Sept &ndash; Dec 2013"
    date_year: "2013"
    description:
        -   "Completed MTV media streaming apps on Windows Phone 8 and Windows RT from scratch"
        -   "Implemented the QR scanner for the CurrentC iOS wallet app"

-   title: "Application Developer"
    company: "NexJ Systems"
    date: "Jan &ndash; Apr 2013"
    date_year: "2013"
    description:
        -   "Implemented features for custom health CRM, and deploying beta to 1000 patients"

-   title: "QA Analyst"
    company: "NexJ Systems"
    date: "May &ndash; Aug 2012"
    date_year: "2012"
    description:
        -   "Assumed QA lead for ATB Investor Services CRM; signed off on beta deployment to 3000 users"
        -   "Developed Python application to automate regression testing PDF files, improving speeds up to 10x"

projects:
-   title: "21 Day Advantage"
    description:
        -   "Windows Phone 8 app based off of Shawn Achor's TEDx Talk with 1000+ downloads"

-   title: "Kinect Voice Controller"
    description:
        -   "Windows WPF application enabling voice activated commands with the Kinect 2.0"

-   title: "UWaterloo Open Data Library"
    description:
        -   "C# wrapper library for UWaterloo's Open Data API"

-   title: "YouTube Playlist Manager"
    description:
        -   "Windows WPF application to manage YouTube subscriptions and playlists using YouTube API"

all_projects:
-
    title: "MASA Windows Store App Base"
    link: "https://github.com/Blisse/Windows8MASA"
    description: ["Project abstractions underlying my random universal apps, glued together by MVVM."]
-
    title: "21 Day Advantage"
    link: "http://www.windowsphone.com/en-us/store/app/21-day-advantage/19cc9347-88a3-4358-a2f7-065a01679145"
    description: ["WP8 app based off of Shawn Achor's TEDx Talk; 1000+ downloads."]
-
    title: "UWaterloo OpenData Library"
    link: "https://github.com/Blisse/UWOpenDataLib"
    description: ["Async C# JSON wrapper around UWaterloo's Open Data API."]
-
    title: "Youtube Subscriber"
    link: "/work/ytsubscriber"
    description: ["Desktop WPF application to parse, display and filter Youtube subscription pages"]
-
    title: "OpenGL Tic-Tac-Toe"
    link: "/work/ogltictactoe"
    description: ["2D OpenGLUT implementation of Tic-Tac-Toe with unbeatable expert level difficulty"]
-
    title: "Beyond Compare 3 Launcher"
    link: "https://github.com/Blisse/BC3Launcher"
    description: ["Automating PDF comparison using Beyond Compare 3"]
-
    title: "This Website"
    link: "/work/site"
    description: ["Fun exploration of web development via Jekyll"]


degree: "Candidate for Bachelor of Software Engineering"
school: "University of Waterloo"
classes:
-   "Expected graduation April 2016"
